libgit - calls
oid_fmt: aByteArray size: anInteger id: objectId

	                                                               ^ self
		                                                                 ffiCall:
			                                                                 #( #void
			                                                                    #git_oid_nfmt
			                                                                    #( #void
			                                                                       #*
			                                                                       #aByteArray
			                                                                       #,
			                                                                       #int
			                                                                       #anInteger
			                                                                       #,
			                                                                       #LGitId
			                                                                       #*
			                                                                       #self ) )