libgit - calls
commit_message: commit

	                                                               ^ self
		                                                                 ffiCallSafely:
		                                                                 #( #void
		                                                                    #*
		                                                                    #git_commit_message
		                                                                    #( #self ) )
		                                                                 options:
		                                                                 #(  )